module.exports.ERROR_TYPES = Object.freeze({
  CHILD_ELEMENT_TYPE_NOT_ALLOWED: 'camunda.childElementTypeNotAllowed',
  ELEMENT_COLLAPSED_NOT_ALLOWED: 'camunda.elementCollapsedNotAllowed',
  ELEMENT_MULTIPLE_NOT_ALLOWED: 'camunda.elementMultipleNotAllowed',
  ELEMENT_TYPE_NOT_ALLOWED: 'camunda.elementTypeNotAllowed',
  ELEMENT_PROPERTY_VALUE_DUPLICATED: 'camunda.elementPropertyValueDuplicated',
  EVENT_BASED_GATEWAY_TARGET_NOT_ALLOWED: 'camunda.eventBasedGatewayTargetNotAllowed',
  EXPRESSION_NOT_ALLOWED: 'camunda.expressionNotAllowed',
  EXPRESSION_REQUIRED: 'camunda.expressionRequired',
  EXPRESSION_VALUE_NOT_ALLOWED: 'camunda.expressionValueNotAllowed',
  EXTENSION_ELEMENT_NOT_ALLOWED: 'camunda.extensionElementNotAllowed',
  EXTENSION_ELEMENT_REQUIRED: 'camunda.extensionElementRequired',
  FEEL_EXPRESSION_INVALID: 'camunda.feelExpressionInvalid',
  LOOP_NOT_ALLOWED: 'camunda.loopNotAllowed',
  ATTACHED_TO_REF_ELEMENT_TYPE_NOT_ALLOWED: 'camunda.attachedToRefElementTypeNotAllowed',
  PROPERTY_DEPENDENT_REQUIRED: 'camunda.propertyDependentRequired',
  PROPERTY_NOT_ALLOWED: 'camunda.propertyNotAllowed',
  PROPERTY_REQUIRED: 'camunda.propertyRequired',
  PROPERTY_TYPE_NOT_ALLOWED: 'camunda.propertyTypeNotAllowed',
  PROPERTY_VALUE_DUPLICATED: 'camunda.propertyValueDuplicated',
  PROPERTY_VALUE_NOT_ALLOWED: 'camunda.propertyValueNotAllowed',
  PROPERTY_VALUE_REQUIRED: 'camunda.propertyValueRequired',
  SECRET_EXPRESSION_INVALID: 'camunda.secretExpressionInvalid'
});